name: Terraform Azure Pipeline

on:
  push:
    branches:
      - cat

  pull_request:
    branches:
      - cat

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Terraform Setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Terraform Version
      - name: Terraform Version
        run: terraform version

      # 4. Terraform Format
      - name: Terraform Format
        run: terraform fmt -check -recursive

      # 5. Azure OIDC Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 6. Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./production

      # 7. Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./production

      # 8. Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./production

      # 9. Terraform Apply
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/cat'
        run: terraform apply -auto-approve
        working-directory: ./production