name: Terraform CI

on:
  push:
    branches:
      - cat

  pull_request:
    branches:
      - cat

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Terraform version
      - name: Terraform Version
        run: terraform version

      # 4. Terraform format
      - name: Terraform Format
        run: terraform fmt -check -recursive

      # 5. Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              ARM_CLIENT_ID: "cc674b5d-a1e6-402f-bd6a-dec7ff2f631d"
              ARM_CLIENT_SECRET: "-K98Q~FKme2iBLPAUQJPWRuZOws~4F-ip0mgbcEN"
              ARM_SUBSCRIPTION_ID: "28b33a86-0366-416d-8614-9dccbe3c193b"
              ARM_TENANT_ID: "0e48a96c-4cf9-4bb4-bf06-2a912f0fc53e"
            }

      # 6. Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./production

      # 7. Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./production

      # 8. Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./production